### ISSUE TITLE
IIFE e parametro riot

### ISSUE THREAD

**Issue by Spartano** [LordKenzo/LearnRiotJS#3]
Se ho capito bene nella prima funzione della IIFE si acceta un parametro, che in questo caso abbiamo chiamato "riot" ma poteva avere qualsiasi nome, invece nella seconda stiamo facendo 3 cose nello stesso tempo, stiamo creando un oggeto, assegno a window una nuova property chiamata riot ed infine stiamo passando lo stesso oggeto come parametro alla prima funzione.

**Comment by LordKenzo** [comment]
La IIFE accetta un parametro (chiamato riot) che viene passato come:
- oggetto vuoto se esiste un oggetto window di tipo object e quindi mi trovo in ambiente browser e pertanto aggancio al globale window l'oggetto riot {}
- l'oggetto exports

Questo PATTERN ha molte varianti ma ognuna di esse ha lo stesso scopo e cioè quella di rendere disponibile la libreria nell'ambiente browser, CommonJS o AMD.
